CREATE TABLE [dbo].[tblDayActivity]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[DayId] UNIQUEIDENTIFIER NOT NULL,
	[ActivityId] UNIQUEIDENTIFIER NOT NULL,
	[Duration] INT NOT NULL,
	[DifficultyLevel] INT NOT NULL
)
