CREATE TABLE [dbo].[tblItem]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(50) NOT NULL, 
    [TypeId] UNIQUEIDENTIFIER NOT NULL, 
    [Calories] INT NOT NULL, 
    [Protein] INT NOT NULL,
    [UserId] UNIQUEIDENTIFIER NULL,
)
